title: Pin Authorization API
baseUri: hb://auth-pin
extends: auth-service-api/auth.raml

types:
  CreatePin:
    type: object
    properties:
      pin_id: string
      time_to_live_seconds?: integer
      pin_length?: integer
      only_digits?: boolean
      identity_keys: object
      extra?: object

  Pin:
    type: object
    properties:
      pin: string
      identity_keys: object
      extra: object
      attempts: integer
      consumed: boolean
      valid_until: # unix date-time in millis
        type: number
        format: int64

  NewPin:
    type: object
    properties:
      pin: string
      pin_id: string

/pins:
  description: |
    Pins to authenticate and authorize requests.
  post:
    description: |
      Create pin to use for the rest authorized requests.
    body:
      application/json: CreatePin
    responses:
      201:
        body:
          application/json: NewPin

