#%RAML 1.0 Extension

# Copyright (c) 2017 Magomed Abdurakhmanov, Hypertino
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

title: Pin Authorization API
baseUri: hb://auth-pin
extends: auth-service-api/auth.raml

types:
  CreatePin:
    type: object
    properties:
      time_to_live_seconds?: integer
      pin_length?: integer
      only_digits?: boolean
      identity_keys: object
      extra?: object

  Pin:
    type: object
    properties:
      pin: string
      identity_keys: object
      extra: object
      attempts: integer
      consumed: boolean
      valid_until: # unix date-time in millis
        type: number
        format: int64

  NewPin:
    type: object
    properties:
      pin_id: string

/pins:
  description: |
    Pins to authenticate and authorize requests.
  post:
    description: |
      Create pin to use for the rest authorized requests.
    body:
      application/json: CreatePin
    responses:
      201:
        body:
          application/json: NewPin

